size: 50
init_data:
  pos_low: [-450.0, 300.0]
  pos_high: [50.0, 600.0]
  vel_low: [0.0, -20.0]
  vel_high: [10.0, 20.0]
params:
  middle_strength: 0.01
  avoid_dist: 100
  match_dist: 10000
  match_strength: 0.125
